### ISSUE TITLE
misa.B behavior

### ISSUE THREAD

**Issue by pdonahue-ventana** [riscv/riscv-b#5]
The [description of misa](https://github.com/riscv/riscv-isa-manual/blob/97f0cf734ca244fe4cca8edbe366a34ad09e5f89/src/machine.adoc?plain=1#L75) says:
> When a standard extension is disabled by clearing its bit in misa, the instructions and CSRs defined or modified by the extension revert to their defined or reserved behaviors as if the extension is not implemented.

This B extension says:
> When misa.B is 0, it indicates that the implementation may not support one or more of the Zba, Zbb, or Zbs extensions.

If software writes 0 to misa.B, what can it expect to happen?  Are all 3 of those extensions disabled or is it implementation-defined which subset are disabled?  The above seems to indicate the latter, though I would expect that if software is writing 0 then it would want to disable everything, or at least have some way of knowing what is disabled.

@ved-rivos

**Comment by ved-rivos** [comment]
`misa.B=1` indicates Zba, Zbb, and Zbs are available. 
`misa.B=0`, one or more of these may not be available. 
If `misa.B` can be written, and is set to 0, then what subset of extensions gets disabled is implementation-defined.

**Comment by pdonahue-ventana** [comment]
> If misa.B can be written, and is set to 0, then what subset of extensions gets disabled is implementation-defined.

That's what I thought.  Yuck.

In a bigger picture way, I don't understand the motivation for this extension.  If we want "consistency and conciseness across toolchains" then why don't we also have a grouping for Zicbom_Zicbop_Zicboz which are also mandated by platforms?  Or V_Zvfhmin_Zvbb_Zvkt?  Or any number of other groups?  Shouldn't we consistently want consistency?

**Comment by ved-rivos** [comment]
The bit manipulation extension was intended to be designated B and its presence reported through `misa.B`.  Clearing B may not lead to Zba/Zbb/Zbs being disabled as that is the backward compatible behavior. This extension is remedial in nature and should have actuall y happened as part of bit manip ratification.

**Comment by pdonahue-ventana** [comment]
In the days of bitmanip 0.93 and earlier there was a plan to have [a B extension](https://github.com/riscv/riscv-bitmanip/blob/b2fd3b8d7d9e43054358b15b1d77011936addb65/texsrc/bext.tex#L77) which was Zba, Zbb, Zbs, Zbc, Zbp, Zbe, Zbf, and Zbm.  But the latter 4 extensions were dropped and the plan for what was "informally" B was abandoned two years ago with https://github.com/riscv/riscv-isa-manual/commit/c1c77c4902d5e7c58613d725d09d66a2a743da1c

> What were formerly informally referred to as the B and J extensions
are instead going to become multiple smaller and disjoint extensions.
Since it appears unlikely that B and J will ultimately have any
meaning, simply mark these misa bits as "reserved", rather than
"tentatively reserved for X".

It sounds like either this change was done in error or the plan has changed back again (or this is being done two years later to accommodate some people who jumped the gun on assuming a B extension like people jumped the gun with vector 0.7.1).  And the definition now also doesn't include Zbc so it doesn't match the past plan (so it wouldn't match the expectation of people who made premature assumptions).

Overall, I think that we should be moving away from relying on misa rather than adding more things to it.  It made sense when there might have only been <26 extensions but we're already far, far beyond that point.  Will the J extension be resurrected similarly?

**Comment by ved-rivos** [comment]
There is no plan to do anything for J. The B is remedial in nature. The Zbc not being included is intentional since the carry less multiplication is not expected to be baseline bit manipulation capability needed by all implementation and especially ones that support Zvbc.

**Comment by pdonahue-ventana** [comment]
OK.  I just wanted to provide some pushback on why this is even useful at all and I wanted to point out that if misa.B is writable then writing it to 0 is of dubious value since you don't really know what's going to happen.  For the latter, the same could be said of misa.M and misa.A now that Zmmul and Zalrsc/Zaamo exist (or will soon), but that could not have been foreseen back when the M and A extensions were defined (unlike with B where we defined subsets before the superset).
